# Generated by Django 4.1.6 on 2023-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("due_date", models.DateTimeField(verbose_name="due date")),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
